project:
  type: book
  output-dir: docs

book:
  title: "Methods (BST 232) Notes"
  author: "Christian Testa"
  chapters:
    - index.qmd
    - week1/week1.qmd

format:
  html:
    theme: style.scss
    number-depth: 0
  pdf:
    documentclass: scrreport
  