<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Methods (BST 232) Notes - 2&nbsp; Week 1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../week2/week2.html" rel="next">
<link href="../index.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-title">Week 1</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Methods (BST 232) Notes</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Methods (BST 232) Notes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week1/week1.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Week 1</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../week2/week2.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Week 2</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#il-famoso-smoking-ra-fisher" id="toc-il-famoso-smoking-ra-fisher" class="nav-link active" data-scroll-target="#il-famoso-smoking-ra-fisher">il famoso Smoking RA Fisher</a></li>
  <li><a href="#hormone-replacement-therapy" id="toc-hormone-replacement-therapy" class="nav-link" data-scroll-target="#hormone-replacement-therapy">Hormone Replacement Therapy</a></li>
  <li><a href="#prediction-studies" id="toc-prediction-studies" class="nav-link" data-scroll-target="#prediction-studies">Prediction Studies</a></li>
  <li><a href="#quantifying-uncertainty" id="toc-quantifying-uncertainty" class="nav-link" data-scroll-target="#quantifying-uncertainty">Quantifying Uncertainty</a></li>
  <li><a href="#why-learn-methods-before-study-design" id="toc-why-learn-methods-before-study-design" class="nav-link" data-scroll-target="#why-learn-methods-before-study-design">Why Learn Methods Before Study Design</a></li>
  <li><a href="#recommended-reading" id="toc-recommended-reading" class="nav-link" data-scroll-target="#recommended-reading">Recommended Reading</a></li>
  <li><a href="#linear-regression" id="toc-linear-regression" class="nav-link" data-scroll-target="#linear-regression">Linear Regression</a>
  <ul class="collapse">
  <li><a href="#hers-study-sbp-in-post-menopausal-women" id="toc-hers-study-sbp-in-post-menopausal-women" class="nav-link" data-scroll-target="#hers-study-sbp-in-post-menopausal-women">HERS Study: SBP in Post-Menopausal Women</a></li>
  <li><a href="#multiple-linear-regression-scalar-notation" id="toc-multiple-linear-regression-scalar-notation" class="nav-link" data-scroll-target="#multiple-linear-regression-scalar-notation">Multiple Linear Regression: Scalar Notation</a></li>
  <li><a href="#vector-notation" id="toc-vector-notation" class="nav-link" data-scroll-target="#vector-notation">Vector Notation</a></li>
  <li><a href="#examples" id="toc-examples" class="nav-link" data-scroll-target="#examples">Examples</a></li>
  <li><a href="#multiple-linear-regression" id="toc-multiple-linear-regression" class="nav-link" data-scroll-target="#multiple-linear-regression">Multiple Linear Regression</a></li>
  <li><a href="#indicator-dummy-variables" id="toc-indicator-dummy-variables" class="nav-link" data-scroll-target="#indicator-dummy-variables">Indicator / Dummy Variables</a></li>
  <li><a href="#polynomial-regressions" id="toc-polynomial-regressions" class="nav-link" data-scroll-target="#polynomial-regressions">Polynomial Regressions</a></li>
  <li><a href="#marginal-associations" id="toc-marginal-associations" class="nav-link" data-scroll-target="#marginal-associations">Marginal Associations</a></li>
  <li><a href="#conditional-association" id="toc-conditional-association" class="nav-link" data-scroll-target="#conditional-association">Conditional Association</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-title">Week 1</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>August 28 — September 1, 2023</p>
<p>“By now you’ve probably figured out this is a class on linear models and generalized linear models”</p>
<p>Office hours: Rachel: Fridays 4-5pm, in-person; Inte: Thursdays 3-4pm, Zoom; Sal: Tuesdays 4-5pm, in-person</p>
<p>Lab time: Fridays: 2-3:30, usually Kresge LL6.</p>
<p>Use the discussion section of Canvas for random questions so everyone has the same access to information.</p>
<p>We’ll assume that students know random variables, hypothesis testing, basic probability, etc.</p>
<p>Kutner et al’s <em>Applied Linear Statistical Models</em> book will be a helpful reference for the first half of the class, while Agresti’s <em>Categorical Data Analysis</em> will be more helpful for the second half of the class.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="standalone_figures/scientific_process/scientific_process.svg" class="img-fluid figure-img" style="width:3.5in"></p>
</figure>
</div>
</div>
</div>
<p>While it would be nice for statisticians to be more often than not included in study design, it’s quite usual that statisticians are often sought out by their colleagues who bring them data that they want to analyze. Hence our class will mostly take an interest in the indicated section of the idealized scientific process, and moreover we’ll assume that we’re often not in a randomized- controlled trial.</p>
<p>We’ll focus on <span class="vocab">associational studies</span>. While it’s almost always the case that when associational studies are performed that investigators are actually interested in are <span class="vocab">causal effects</span>. However, in this class we’ll tend not to talk about causal effects or “causal” -anything because these days causal inference tends to refer to a specific set of methods used in observational causal inference.</p>
<p>We’ll be concerned quite substantively around confounding.</p>
<section id="il-famoso-smoking-ra-fisher" class="level2">
<h2 class="anchored" data-anchor-id="il-famoso-smoking-ra-fisher">il famoso Smoking RA Fisher</h2>
<p>We’ll talk about a lot of the methods that Ronald A. Fisher developed. Already in the 1900s it was being observed that there was a strong association between smoking and lung cancer. However, Fisher was a smoker himself and posited that the association between lung cancer and smoking could be explained away by some genetic or biological difference between the smoking and non-smoking population (positing some genes that caused people to desire to smoke).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="standalone_figures/confounding/smoking_confounding.svg" class="img-fluid figure-img" style="width:3.5in"></p>
<p></p><figcaption class="figure-caption">Ronald Fisher’s unsupported theory of genetics confounding the smoking-lung cancer relationship</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>We’re pretty sure that this was driven not by any substance matter expertise, but rather by Fisher’s love of smoking.</p>
</section>
<section id="hormone-replacement-therapy" class="level2">
<h2 class="anchored" data-anchor-id="hormone-replacement-therapy">Hormone Replacement Therapy</h2>
<p>In the mid- to late- 20th century there were a ton of studies linking hormone replacement therapy for older women to better cardiovascular outcomes (lack of coronary heart disease).</p>
<p>However, thankfully due to the Heart and Estrogen/Progestin Study (HERS, in the early 90s) we now know that a lot of those studies were not controlling for socioeconomic status. It turns out that socioeconomic status was highly associated with HRT usage, and associated at least in the US with a lot of better health outcomes across the board.</p>
<p>It turned out that HRT when applied at certain times for some people can actually be harmful — but the point is the picture is much muddier than was initially thought and recommendations were rolled back. Later randomized studies were performed that produced reliable bodies of evidence demonstrating either no effect or in some cases harmful effects.</p>
<p>We’ll use the baseline data from HERS (not so much interested in the HRT treatment effect), but to investigate the research question:</p>
<blockquote class="blockquote">
<p>How is systolic blood pressure related to age, independently of other well-known cardiovascular risk factors? (Age, diabetes, smoking, etc.)</p>
</blockquote>
</section>
<section id="prediction-studies" class="level2">
<h2 class="anchored" data-anchor-id="prediction-studies">Prediction Studies</h2>
<p>Typically in prediction settings, there’s no single exposure of particular interest; mechanisms and confounding is treated as less of a concern (if at all), and the main challenge is that we need to take care to not <span class="vocab">overfit</span> the data.</p>
<p>A major theme of this class will be that different tasks require different analysis strategies and diffrent statistical tools.</p>
</section>
<section id="quantifying-uncertainty" class="level2">
<h2 class="anchored" data-anchor-id="quantifying-uncertainty">Quantifying Uncertainty</h2>
<p>Typically standard statistical models have nice theoretical properties because years-and-years ago, we didn’t have much data so people spent their time studying theory instead of data. As a result, we have a lot of nice theories about the uncertainty represented in statistical models.</p>
<p>An example of the kind of uncertainty we might be interested in is shown in this figure relating Alzheimer’s disease rates and exposure to PM<sub>2.5</sub>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="standalone_figures/pm2.5/pm25.jpg" class="img-fluid figure-img" style="width:4in"></p>
</figure>
</div>
</div>
</div>
<p>This figure is taken from the article <a href="https://www.thelancet.com/journals/lanplh/article/PIIS2542-5196(20)30227-8/fulltext"><em>Long-term effects of PM2·5 on neurological disorders in the American Medicare population: a longitudinal cohort study</em> by Shi et al, Lancet Planetary Health (2020)</a>.</p>
</section>
<section id="why-learn-methods-before-study-design" class="level2">
<h2 class="anchored" data-anchor-id="why-learn-methods-before-study-design">Why Learn Methods Before Study Design</h2>
<p>An interesting point made is that it’s important to understand the limitations, strengths of methods, what they can and can’t do, and how to use them before designing a study.</p>
</section>
<section id="recommended-reading" class="level2">
<h2 class="anchored" data-anchor-id="recommended-reading">Recommended Reading</h2>
<p>Kutner M, Nachtsheim C, Neter J, Li W. Applied Linear Statistical Model. 5th edition. chapters 1-3</p>
<p>Shmueli, G. (2010). To explain or to predict? <em>Statistical Science.</em> <a href="https://www.stat.berkeley.edu/~aldous/157/Papers/shmueli.pdf" class="uri">https://www.stat.berkeley.edu/~aldous/157/Papers/shmueli.pdf</a></p>
</section>
<section id="linear-regression" class="level1">
<h1>Linear Regression</h1>
<p>We will generally be intereseted in the relationship between an outcome <span class="math inline">\(Y\)</span> and <span class="math inline">\(p\)</span> covariates or predictors denoted <span class="math inline">\((x_1, ..., x_p)\)</span>.</p>
<p>We generally say that a statistical model has a <em>systematic</em> component and a <em>random</em> component.</p>
<p>We often hypothesize that the “real” relationship between our outcome and predictors might be “<em>super-complex</em>”. Like cancer and environmental exposures might have complex dependencies on genetics, etc.. So sometimes instead of having a systematic component that captures variables in their full complexity, we might prioritize interpretability and we might be satisfied with an imperfect (but more intuitive, simpler) model that might give us some intuition about reality.</p>
<p>The random component may provide both a means to explain everything uncaptured by our predictors, as well as “real” randomness. For example, we might theorize that every time cells divide, there’s some small chance due to genetic drift that cells become metastatic and cancerous which is just random (did a mutation happen that was harmful in the right way in the right spot?).</p>
<section id="hers-study-sbp-in-post-menopausal-women" class="level2">
<h2 class="anchored" data-anchor-id="hers-study-sbp-in-post-menopausal-women">HERS Study: SBP in Post-Menopausal Women</h2>
<p>In a clinical trial of hormone therapy for preventing heart attacks and deaths among 2,763 post-menopausal women with existing coronary heart disease:</p>
<ul>
<li>the outcome variable is systolic blood pressure</li>
<li>the data collected on covariates included age, diabetes diagnosis, smoking status, etc.</li>
<li>the research question was how is systolic blood pressure jointly related to age, statin use, and other risk factors in this cohort.</li>
</ul>
<p>Reference: Vittinghoff et al., <em>Regression methods in Biostatistics 2005</em> <a href="https://regression.ucsf.edu/regression-methods-biostatistics-linear-logistic-survival-and-repeated-measures-models" class="uri">https://regression.ucsf.edu/regression-methods-biostatistics-linear-logistic-survival-and-repeated-measures-models</a></p>
</section>
<section id="multiple-linear-regression-scalar-notation" class="level2">
<h2 class="anchored" data-anchor-id="multiple-linear-regression-scalar-notation">Multiple Linear Regression: Scalar Notation</h2>
<p>We consider the model</p>
<p><span class="math display">\[Y_i = \beta_0 + \beta_1 x_{i1} + ... + \beta_p x_{ip} + \epsilon_i, \quad i = 1, ..., n.\]</span></p>
<p><span class="math display">\[\mathbb E(\epsilon_i) = 0, \, \underbrace{\text{Var}(\epsilon_i) = \sigma^2}_{\text{homoscedasticity assumption}}, \, \text{ and Cov}(\epsilon_i, \epsilon_j) = 0.\]</span></p>
<p>Typically we assume that the predictors <span class="math inline">\(x_i\)</span> are fixed and measured without error.</p>
<p>We require that <span class="math inline">\(p &lt; n\)</span>.</p>
<p>TJ notes that <span class="math inline">\(\text{Cov}(\epsilon_i, \epsilon_j) = 0\)</span> doesn’t imply independence. This is the assumption we’re making for the time-being, but independence will be implied after we later assume that the errors are normally distributed.</p>
<p>Roman asks if we need a conditional mean zero assumption — i.e., <span class="math inline">\(\mathbb E(\epsilon | x) = 0\)</span>? Rachel notes that <span class="math inline">\(\epsilon\)</span> and <span class="math inline">\(x\)</span> are assumed to be independent, so <span class="math inline">\(\mathbb E(\epsilon | x) = \epsilon\)</span>. We will make stronger assumptions later, but we aren’t introducing those yet.</p>
<p>By taking the expected value of both sides, we can equivalently write that</p>
<p><span class="math display">\[\mathbb E(Y_i) = \beta_0 + \beta_1 x_{i1} + ... + \beta_p x_{ip}.\]</span></p>
<p>The parameters <span class="math inline">\(\beta_j\)</span> for <span class="math inline">\(j = 1, ..., p\)</span> represent the change in the expected value <span class="math inline">\(\mathbb E(Y_i)\)</span> per unit change in <span class="math inline">\(x_j\)</span> holding the remaining predictors <span class="math inline">\(x_k \, (k \neq j)\)</span> constant.</p>
<p>One can see this by observing:</p>
<p><span class="math display">\[ \mathbb E(Y_i | x_{i1} = x^* + 1) = \beta_0 + \beta_1 (x^* + 1) + ...\]</span> <span class="math display">\[ \mathbb E(Y_i | x_{i1} = x^*) = \beta_0 + \beta_1 x^* + ...\]</span> <span class="math display">\[ \mathbb E(Y_i | x_{i1} = x^* + 1) - \mathbb E(Y_i | x_{i1} = x^*) = \beta_1.\]</span></p>
<p>We most often interested in testing whether <span class="math inline">\(\beta_j = 0\)</span>, interpreted as a test of whether there’s an association between <span class="math inline">\(x_j\)</span> and <span class="math inline">\(Y\)</span>.</p>
</section>
<section id="vector-notation" class="level2">
<h2 class="anchored" data-anchor-id="vector-notation">Vector Notation</h2>
<p>We can write this model more succinctly by writing:</p>
<p><span class="math display">\[ Y_i = x_i' \beta + \epsilon_i, \quad i = 1, ..., n,\]</span></p>
<p>where <span class="math inline">\(x_i = (1, x_{i1}, ..., x_{ip})',\)</span> and <span class="math inline">\(\beta = (\beta_0, \beta_1, ..., \beta_p)'\)</span>, <span class="math inline">\(\mathbb E(\epsilon_i) = 0\)</span>, <span class="math inline">\(\text{Var}(\epsilon_i) = \sigma^2\)</span>, and <span class="math inline">\(\text{Cov}(\epsilon_i, \epsilon_j) = 0\)</span>.</p>
</section>
<section id="examples" class="level2">
<h2 class="anchored" data-anchor-id="examples">Examples</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>here() starts at /Users/cht180/Documents/2023/MethodsBST232</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.2     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.1     </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>hers <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data/hers.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 2763 Columns: 40
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (16): HT, raceth, nonwhite, smoking, drinkany, exercise, physact, globra...
dbl (24): age, medcond, weight, BMI, waist, WHR, glucose, weight1, BMI1, wai...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>plt1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(hers <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">sample_frac</span>(.<span class="dv">1</span>), <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> SBP)) <span class="sc">+</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Scatterplot of a 10% sample of our data"</span>) </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>plt1 </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="week1_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>plt2 <span class="ot">&lt;-</span> plt1 <span class="sc">+</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary_bin</span>(<span class="at">bins =</span> <span class="dv">10</span>, <span class="at">breaks =</span> <span class="fu">quantile</span>(hers<span class="sc">$</span>age, <span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">1</span>, <span class="fl">0.1</span>)), <span class="at">geom =</span> <span class="st">'line'</span>, <span class="at">fun =</span> mean, <span class="at">color =</span> <span class="st">'cadetblue'</span>, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span> </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary_bin</span>(<span class="at">bins =</span> <span class="dv">10</span>, <span class="at">breaks =</span> <span class="fu">quantile</span>(hers<span class="sc">$</span>age, <span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">1</span>, <span class="fl">0.1</span>)), <span class="at">geom =</span> <span class="st">'point'</span>, <span class="at">shape =</span> <span class="dv">23</span>, <span class="at">fun =</span> mean, <span class="at">color =</span> <span class="st">'black'</span>, <span class="at">size =</span> <span class="fl">3.5</span>, <span class="at">fill =</span> <span class="st">'white'</span>) <span class="sc">+</span> </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Now with overlain means for decile groups by age"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>plt2 </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="week1_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>plt3 <span class="ot">&lt;-</span> </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  plt2 <span class="sc">+</span> </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span> </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Now with a linear model"</span>) </span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>plt3 </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="week1_files/figure-html/unnamed-chunk-4-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>lm.sbp.age <span class="ot">&lt;-</span> <span class="fu">lm</span>(SBP <span class="sc">~</span> age, <span class="at">data =</span> hers)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>jtools<span class="sc">::</span><span class="fu">summ</span>(lm.sbp.age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<tbody>
  <tr>
   <td style="text-align:left;font-weight: bold;"> Observations </td>
   <td style="text-align:right;"> 2763 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> Dependent variable </td>
   <td style="text-align:right;"> SBP </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> Type </td>
   <td style="text-align:right;"> OLS linear regression </td>
  </tr>
</tbody>
</table> <table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<tbody>
  <tr>
   <td style="text-align:left;font-weight: bold;"> F(1,2761) </td>
   <td style="text-align:right;"> 77.21 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> R² </td>
   <td style="text-align:right;"> 0.03 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> Adj. R² </td>
   <td style="text-align:right;"> 0.03 </td>
  </tr>
</tbody>
</table> <table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0;">
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:right;"> Est. </th>
   <th style="text-align:right;"> S.E. </th>
   <th style="text-align:right;"> t val. </th>
   <th style="text-align:right;"> p </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;font-weight: bold;"> (Intercept) </td>
   <td style="text-align:right;"> 103.63 </td>
   <td style="text-align:right;"> 3.60 </td>
   <td style="text-align:right;"> 28.82 </td>
   <td style="text-align:right;"> 0.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> age </td>
   <td style="text-align:right;"> 0.47 </td>
   <td style="text-align:right;"> 0.05 </td>
   <td style="text-align:right;"> 8.79 </td>
   <td style="text-align:right;"> 0.00 </td>
  </tr>
</tbody>
<tfoot><tr><td style="padding: 0; " colspan="100%">
<sup></sup> Standard errors: OLS</td></tr></tfoot>
</table>
</div>
</div>
<p>So now we would say that <span class="math inline">\(\hat{\mathbb E}(SBP_i) = 103.63 + 103.63 Age_i\)</span>. Though, the intercept is kind of useless since our model doesn’t have any observations for systolic blood pressure for age 0 infants. We might want to fit an age centered model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>lm.sbp.agec <span class="ot">&lt;-</span> <span class="fu">lm</span>(SBP <span class="sc">~</span> <span class="fu">I</span>(age <span class="sc">-</span> <span class="fu">mean</span>(age)), <span class="at">data =</span> hers)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>jtools<span class="sc">::</span><span class="fu">summ</span>(lm.sbp.agec)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<tbody>
  <tr>
   <td style="text-align:left;font-weight: bold;"> Observations </td>
   <td style="text-align:right;"> 2763 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> Dependent variable </td>
   <td style="text-align:right;"> SBP </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> Type </td>
   <td style="text-align:right;"> OLS linear regression </td>
  </tr>
</tbody>
</table> <table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<tbody>
  <tr>
   <td style="text-align:left;font-weight: bold;"> F(1,2761) </td>
   <td style="text-align:right;"> 77.21 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> R² </td>
   <td style="text-align:right;"> 0.03 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> Adj. R² </td>
   <td style="text-align:right;"> 0.03 </td>
  </tr>
</tbody>
</table> <table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0;">
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:right;"> Est. </th>
   <th style="text-align:right;"> S.E. </th>
   <th style="text-align:right;"> t val. </th>
   <th style="text-align:right;"> p </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;font-weight: bold;"> (Intercept) </td>
   <td style="text-align:right;"> 135.07 </td>
   <td style="text-align:right;"> 0.36 </td>
   <td style="text-align:right;"> 378.24 </td>
   <td style="text-align:right;"> 0.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> I(age - mean(age)) </td>
   <td style="text-align:right;"> 0.47 </td>
   <td style="text-align:right;"> 0.05 </td>
   <td style="text-align:right;"> 8.79 </td>
   <td style="text-align:right;"> 0.00 </td>
  </tr>
</tbody>
<tfoot><tr><td style="padding: 0; " colspan="100%">
<sup></sup> Standard errors: OLS</td></tr></tfoot>
</table>
</div>
</div>
<p>In which case we’d say that <span class="math inline">\(\hat{\mathbb E}(SBP_i) = 135.07 + 135.07 Age_i\)</span>.</p>
</section>
<section id="multiple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="multiple-linear-regression">Multiple Linear Regression</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fitting a p=2 model</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>lm.sbp.age.weight <span class="ot">&lt;-</span> <span class="fu">lm</span>(SBP <span class="sc">~</span> age <span class="sc">+</span> weight, <span class="at">data =</span> hers)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> y <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">100</span>, <span class="at">length=</span> <span class="dv">30</span>)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="cf">function</span>(x,y){ z <span class="ot">&lt;-</span> x<span class="sc">*</span><span class="fu">coef</span>(lm.sbp.age.weight)[<span class="dv">2</span>] <span class="sc">+</span> y<span class="sc">*</span><span class="fu">coef</span>(lm.sbp.age.weight)[<span class="dv">3</span>] <span class="sc">+</span> <span class="fu">coef</span>(lm.sbp.age.weight)[<span class="dv">1</span>] }</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">outer</span>(x,y,f)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="fu">persp</span>(x, y, z, <span class="at">theta =</span> <span class="dv">30</span>, <span class="at">phi =</span> <span class="dv">30</span>, <span class="at">expand =</span> <span class="fl">0.5</span>, <span class="at">col =</span> <span class="st">"lightblue"</span>, <span class="at">xlab =</span> <span class="st">"age"</span>, <span class="at">ylab =</span> <span class="st">"weight"</span>, <span class="at">zlab =</span> <span class="st">"expected SBP"</span>, <span class="at">ticktype =</span> <span class="st">'detailed'</span>, <span class="at">nticks =</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="week1_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="indicator-dummy-variables" class="level2">
<h2 class="anchored" data-anchor-id="indicator-dummy-variables">Indicator / Dummy Variables</h2>
<p>We might be interested in modeling categorical variables as well. To do so, we would include dummy variables.</p>
<p>If a categorical variable has <span class="math inline">\(K\)</span> levels, then we’ll need to compute <span class="math inline">\(K-1\)</span> dummy variables where the omitted variable is called the “reference level”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(hers<span class="sc">$</span>physact)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "much more active"     "much less active"     "about as active"     
[4] "somewhat less active" "somewhat more active"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>hers<span class="sc">$</span>physact <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(hers<span class="sc">$</span>physact) </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="co"># the reference category will be "much more active" since it's the </span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="co"># first factor level — </span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># if we wanted to change it, we could run: </span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="co"># hers$raceth &lt;- relevel(hers$raceth, "much less active") </span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="co"># for example. </span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>lm.sbp.physact <span class="ot">&lt;-</span> <span class="fu">lm</span>(SBP <span class="sc">~</span> physact, <span class="at">data =</span> hers)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">model.matrix</span>(lm.sbp.physact))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept) physactmuch less active physactmuch more active
1           1                       0                       1
2           1                       1                       0
3           1                       0                       0
4           1                       1                       0
5           1                       0                       0
6           1                       0                       0
  physactsomewhat less active physactsomewhat more active
1                           0                           0
2                           0                           0
3                           0                           0
4                           0                           0
5                           1                           0
6                           0                           0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>jtools<span class="sc">::</span><span class="fu">summ</span>(lm.sbp.physact)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<tbody>
  <tr>
   <td style="text-align:left;font-weight: bold;"> Observations </td>
   <td style="text-align:right;"> 2763 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> Dependent variable </td>
   <td style="text-align:right;"> SBP </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> Type </td>
   <td style="text-align:right;"> OLS linear regression </td>
  </tr>
</tbody>
</table> <table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<tbody>
  <tr>
   <td style="text-align:left;font-weight: bold;"> F(4,2758) </td>
   <td style="text-align:right;"> 0.48 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> R² </td>
   <td style="text-align:right;"> 0.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> Adj. R² </td>
   <td style="text-align:right;"> -0.00 </td>
  </tr>
</tbody>
</table> <table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0;">
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:right;"> Est. </th>
   <th style="text-align:right;"> S.E. </th>
   <th style="text-align:right;"> t val. </th>
   <th style="text-align:right;"> p </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;font-weight: bold;"> (Intercept) </td>
   <td style="text-align:right;"> 135.00 </td>
   <td style="text-align:right;"> 0.63 </td>
   <td style="text-align:right;"> 215.01 </td>
   <td style="text-align:right;"> 0.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> physactmuch less active </td>
   <td style="text-align:right;"> 0.07 </td>
   <td style="text-align:right;"> 1.49 </td>
   <td style="text-align:right;"> 0.05 </td>
   <td style="text-align:right;"> 0.96 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> physactmuch more active </td>
   <td style="text-align:right;"> -0.90 </td>
   <td style="text-align:right;"> 1.26 </td>
   <td style="text-align:right;"> -0.72 </td>
   <td style="text-align:right;"> 0.47 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> physactsomewhat less active </td>
   <td style="text-align:right;"> 0.96 </td>
   <td style="text-align:right;"> 1.06 </td>
   <td style="text-align:right;"> 0.91 </td>
   <td style="text-align:right;"> 0.36 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> physactsomewhat more active </td>
   <td style="text-align:right;"> -0.05 </td>
   <td style="text-align:right;"> 0.91 </td>
   <td style="text-align:right;"> -0.05 </td>
   <td style="text-align:right;"> 0.96 </td>
  </tr>
</tbody>
<tfoot><tr><td style="padding: 0; " colspan="100%">
<sup></sup> Standard errors: OLS</td></tr></tfoot>
</table>
</div>
</div>
<p>In machine learning this is called <a href="https://en.wikipedia.org/wiki/One-hot">“one-hot” encoding</a>.</p>
</section>
<section id="polynomial-regressions" class="level2">
<h2 class="anchored" data-anchor-id="polynomial-regressions">Polynomial Regressions</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>lm.sbp.agepolynomial <span class="ot">&lt;-</span> <span class="fu">lm</span>(SBP <span class="sc">~</span> <span class="fu">poly</span>(age), <span class="at">data =</span> hers)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="co"># we could plug in coef(lm.sbp.agepolynomial)[1] through </span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co"># coef(lm.sbp.agepolynomial)[4] into the following equation, </span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="co"># but it's kind of boring — instead here's a more fun </span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="co"># looking cubic polynomial we could imagine being the result of</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="co"># a polynomial regression:</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="dv">1</span> <span class="sc">-</span> <span class="fl">2.8</span><span class="sc">*</span>x <span class="sc">+</span> <span class="dv">4</span><span class="sc">*</span>(x<span class="sc">^</span><span class="dv">2</span>) <span class="sc">-</span> .<span class="dv">65</span><span class="sc">*</span>(x<span class="sc">^</span><span class="dv">3</span>), <span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> <span class="dv">5</span>,</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">xlab =</span> <span class="fu">expression</span>(x[<span class="dv">1</span>]),</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">ylab =</span> <span class="st">"E(Y)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="week1_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>It’s worth emphasizing that usually we prefer splines or generalized additive models to polynomial regression these days since polynomial regression can act strangely.</p>
</section>
<section id="marginal-associations" class="level2">
<h2 class="anchored" data-anchor-id="marginal-associations">Marginal Associations</h2>
<p>If we have one binary predictor <span class="math inline">\(x_1\)</span> and one continuous <span class="math inline">\(x_2\)</span>, we might be interested in the <em>marginal association</em> between <span class="math inline">\(Y\)</span> and <span class="math inline">\(x_2\)</span>. This would look like a model fit with <code>lm(Y ~ x2)</code> and <span class="math inline">\(x_1\)</span> is not included.</p>
</section>
<section id="conditional-association" class="level2">
<h2 class="anchored" data-anchor-id="conditional-association">Conditional Association</h2>
<p>We might also want to fit models that include <span class="math inline">\(x_1\)</span>, so those could be fit with <code>lm(Y ~ x1 + x2)</code> and this would include an effect for <span class="math inline">\(x_2\)</span> (one effect, not multiple) that is applied while also considering an effect for <span class="math inline">\(x1\)</span>.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../index.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Methods (BST 232) Notes</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../week2/week2.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-title">Week 2</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>